### ISSUE TITLE
Upgrade to latest pdftron

### ISSUE THREAD

**Issue by devopsmica** [Acen/PDFNet-PHP-Docker#3]
Hi, 

would it be possible to update the image to the latest version of pdftron?

https://www.pdftron.com/documentation/ios/changelog/v7-1-0-74382/

Thanks,

**Comment by Acen** [comment]
Thanks for notifying me.
Sure, I'll have a chance to look into it pretty shortly.

Feel free to make a PR if you have the time.

https://www.pdftron.com/documentation/linux/changelog/

**Comment by devopsmica** [comment]
Thanks a lot!
